### ISSUE TITLE
투표 페이지 - 투표 가능 날짜가 많을 때 스크롤 가능 영역 변경

### ISSUE THREAD

**Issue by EarlyHail** [Team-Panopticon/TBD-client#154]
- 투표 가능 날짜가 많을 때, (투표현황 + 캘린더) 영역과 전체 페이지 모두에 스크롤이 생김

- 모임 이름, 버튼을 제외한 body 영역의 스크롤만 남기기
   - 모임이름만 Header, 버튼만 Footer로 하고 나머지는 모두 body 영역에서 scroll

- 재현 환경 
    - iOS 실기기 / Simulator
    - Chrome / Safari

**Comment by juyoungpark718** [comment]
요거 고쳐진거 같은데요..? 제가 이해를 잘 못한걸까요. @EarlyHail
