### ISSUE TITLE
특정 환경에서 공유하기 기능이 동작하지 않음

### ISSUE THREAD

**Issue by EarlyHail** [Team-Panopticon/TBD-client#167]
- 특정 환경에서 공유하기 기능 불가
    - 메시지: 복사를 다시 시도해주세요

### 특이사항

- 재현 환경: AOS / 카톡 인앱 브라우저
- iOS & AOS 삼브 & 크롬은 정상 동작

**Comment by saeeng** [comment]
https://kyounghwan01.github.io/blog/React/clipboard-copy/#%E1%84%8B%E1%85%A8%E1%84%89%E1%85%B5-%E1%84%8F%E1%85%A9%E1%84%83%E1%85%B3

**Comment by EarlyHail** [comment]
https://web.dev/i18n/ko/async-clipboard/

https://velog.io/@sjsrkdgks/%EC%9B%B9%EC%95%B1-%ED%81%B4%EB%A6%BD%EB%B3%B4%EB%93%9C-%EB%B3%B5%EC%82%AC%EA%B8%B0%EB%8A%A5

**Comment by EarlyHail** [comment]
참고: 유튜브 copy 코드

```js
 a = document.getElementById(a.toString());
            a.focus();
            a.setSelectionRange(0, a.value.length);
            try {
                var b = document.execCommand("copy")
            } catch (c) {}
            _.XM(function() {
                b ? _.po(gxa) : _.po(hxa)
            })
```

**Comment by juyoungpark718** [comment]
https://web.dev/async-clipboard/
