### ISSUE TITLE
공유하기 modal 등장 / 사라짐 애니메이션 추가

### ISSUE THREAD

**Issue by EarlyHail** [Team-Panopticon/TBD-client#168]
- 하단 공유하기 modal이 올라오고 없어질때 애니메이션이 있으면 좋을듯
    - iOS / Chrome 에서 애니메이션 안보임
    - iOS / Kakao Browser 에서는 보임

**Comment by junsushin-dev** [comment]
iOS / Safari 에서는 보임

**Comment by junsushin-dev** [comment]
테스트 결과 MUI의 drawer 이슈로 보임 (MUI 홈페이지에서도 동일한 이슈)
외부 라이브러리 이슈이기 때문에 Close 처리
