### ISSUE TITLE
투표테이블 클릭시 오작동

### ISSUE THREAD

**Issue by saeeng** [Team-Panopticon/TBD-client#179]
투표 테이블 클릭시

1. 빠르게 3 개의 날을 연속하여 클릭
2. 두번째 누른 날이 첫번째 누른날의 해제로 작동함

**Comment by junsushin-dev** [comment]
이런 이슈 회사에서 봤었는데, iOS 쪽 브라우저가 근본적인 문제였던 것으로 기억이 나네요

**Comment by junsushin-dev** [comment]
https://github.com/facebook/react/issues/19841
