### ISSUE TITLE
랜딩 페이지 및 새모임 만들기 기획 필요

### ISSUE THREAD

**Issue by saeeng** [Team-Panopticon/TBD-client#254]
랜딩페이지 필요해보임

모임을 만들기 위한 버튼이 없음..

**Comment by junsushin-dev** [comment]
헤더에 새 모임 만들러 가는 로고 버튼 추가

**Comment by junsushin-dev** [comment]
GPT4 & DALLE 로 만든 로고 이미지

![DALL·E 2023-11-22 21 39 22 - Design a logo for an app called 'Motoo', represented by the domain https___motoo day  The app specializes in scheduling lunch or dinner with friends b](https://github.com/Team-Panopticon/TBD-client/assets/32405358/6f34b52d-af2e-43ef-866d-b8f778b8adc1)

**Comment by saeeng** [comment]
![motooday-high-resolution-logo-transparent](https://github.com/Team-Panopticon/TBD-client/assets/41819176/f8ff61d4-f070-482f-b66f-cf8234cec1f2)
![motooday-high-resolution-logo](https://github.com/Team-Panopticon/TBD-client/assets/41819176/d91f6e18-8f57-44cc-b508-4881cfad03ec)

**Comment by junsushin-dev** [comment]
랜딩페이지 추가 완료 

https://github.com/Team-Panopticon/TBD-client/pull/270

**Comment by saeeng** [comment]
새모임 만들기 메뉴 추가 완료
