### ISSUE TITLE
투표 생성 Validation

### ISSUE THREAD

**Issue by EarlyHail** [Team-Panopticon/TBD-client#59]
- input 시 validation
  - [x] 모임 이름: string, length >= 1
  - [x] 모임 날짜: ISODateString, not empty, 오늘 이후
  - [x] 모임 유형: string, 'date' | 'meal' 둘중 하나 필수선택
  - [x] 투표 마감: ISODateString, 오늘 이후
  - [ ] 비밀번호: undefined / length = 4, digit으로만 이루어져야 함

- [ ] 서버 요청 이전 validation

**Comment by EarlyHail** [comment]
### 비밀번호 관련 validation

#### client-side

- 비밀번호 : 0글자일때 undefined, 4글자일 때 입력 가능

  이외에는 진행이 안되어야함

- 0글자일 때는 생략하기 버튼과 취소 버튼

- 4글자일 때는 설정하기와 취소버튼

- 버튼 구조

  - 현재: `생략하기 | 설정하기`

  - 변경: `취소 | 생략하기` and `취소 | 설정하기`

    - 0글자: `취소 | 생략하기`
    - 1~3글자: `취소 | 설정하기(disabled)`
    - 4글자: `취소 | 설정하기(active)`

- 취소 버튼

  - 명확한 취소버튼 - 👍

  - 우상단 X버튼

  - 외부 클릭 - 👎

#### server-side

- DTO에 password 필드가 아예 없거나 null일 경우에는 OK
- DTO에 password 필드가 length 4, '0-9' 글자로만 구성된 경우 OK

**Comment by junsushin-dev** [comment]
Validation을 언제 해야할까?

- 각 input에서 다음 단계로 넘기기 전에 (다음버튼 활성화로 표시)
- 생성하기 버튼 누를 때 -> password 제외 전체적으로 validation (버튼 활성화로 표시)
- password modal에서는 password만 validation 수행 (버튼 활성화로 표시)
- onConfirm 호출 시에는 createMeetingStore + password 파라미터로 호출

**Comment by junsushin-dev** [comment]
![Image](https://user-images.githubusercontent.com/32405358/222871832-df183a05-fe53-4f28-880b-3191052cf707.png)

**Comment by EarlyHail** [comment]
### createMeeting 상태 undefined 추가

처음 상태와 사용자가 입력한 값을 지웠을 때를 구분하기 위해서 createMeeting 상태의 기본값을 undefined로 설정

- undefined일 때 -> 한번도 입력 안한 상태 -> 밸리데이선 문구 미노출
- 빈 문자열인 경우 -> 입력했다가 지운 상태 -> 밸리데이션 문구 노출
